### ISSUE TITLE
the order in which you throw eyes might matter?

### ISSUE THREAD

**Issue by mskrss** [Ninjabrain1/Ninjabrain-Bot#62]
these weren't real measurements, but still i'd imagine the result should be the same
![image](https://github.com/Ninjabrain1/Ninjabrain-Bot/assets/97827489/7deda09f-ee3a-4a9c-9641-164ba3a30d28)

i also tested it with real measurements and the results were the exact same:
![image](https://github.com/Ninjabrain1/Ninjabrain-Bot/assets/97827489/590b7c46-eb91-4d81-a722-1ab8dfa55c93)

i don't really understand how it works, but i'd imagine the first situation can maybe occur in a run and it seems like unintentional behavior to me? idk if it really matters

0.0046 standard deviation btw

**Comment by Ninjabrain1** [comment]
@mskrss Yes, the order matters (but usually not). The eye will always point to the closest stronghold, which means that it is impossible for the stronghold to be too far away from you, and this is accounted for by my algorithm. The max distance depends on where exactly youre standing when throwing the eye, and which direction the eye points. However, the algorithm only takes this into account for the first throw, since your other throws should always be closer to the stronghold, or approximately the same distance, as the first.

This is likely what happened, 3303 blocks is very far, swapping the throws makes this distance even further, and probably increases the distance such that it is impossible for the stronghold to be that far. This only happens with fake measurements.
